///|
pub impl Show for Disposable with output(_self, _logger) {

}

///|
pub impl Eq for Disposable with equal(lhs, rhs) {
  physical_equal(lhs, rhs)
}

///|
pub impl ToJson for Disposable with to_json(_self) {
  Json::null()
}

///|
pub impl Show for TextEditorEdit with output(_self, _logger) {

}

///|
pub impl Eq for TextEditorEdit with equal(lhs, rhs) {
  physical_equal(lhs, rhs)
}

///|
pub impl ToJson for TextEditorEdit with to_json(_self) {
  Json::null()
}

///|
pub impl Show for RegExp with output(_self, _logger) {

}

///|
pub impl Eq for RegExp with equal(lhs, rhs) {
  physical_equal(lhs, rhs)
}

///|
pub impl ToJson for RegExp with to_json(_self) {
  Json::null()
}

///|
pub impl[T] Show for Thenable[T] with output(_self, _logger) {

}

///|
pub impl[T] Eq for Thenable[T] with equal(lhs, rhs) {
  physical_equal(lhs, rhs)
}

///|
pub impl[T] ToJson for Thenable[T] with to_json(_self) {
  Json::null()
}

///|
pub impl[T] Show for Event[T] with output(_self, _logger) {

}

///|
pub impl[T] Eq for Event[T] with equal(lhs, rhs) {
  physical_equal(lhs, rhs)
}

///|
pub impl[T] ToJson for Event[T] with to_json(_self) {
  Json::null()
}

///|
pub impl Show for FileSystem with output(_self, _logger) {

}

///|
pub impl Eq for FileSystem with equal(lhs, rhs) {
  physical_equal(lhs, rhs)
}

///|
pub impl ToJson for FileSystem with to_json(_self) {
  Json::null()
}

///|
pub impl Show for WorkspaceConfiguration with output(_self, _logger) {

}

///|
pub impl Eq for WorkspaceConfiguration with equal(lhs, rhs) {
  physical_equal(lhs, rhs)
}

///|
pub impl ToJson for WorkspaceConfiguration with to_json(_self) {
  Json::null()
}

///|
pub impl[T] Show for Progress[T] with output(_self, _logger) {

}

///|
pub impl[T] Eq for Progress[T] with equal(lhs, rhs) {
  physical_equal(lhs, rhs)
}

///|
pub impl[T] ToJson for Progress[T] with to_json(_self) {
  Json::null()
}

///|
pub impl Show for QuickInputButtons with output(_self, _logger) {

}

///|
pub impl Eq for QuickInputButtons with equal(lhs, rhs) {
  physical_equal(lhs, rhs)
}

///|
pub impl ToJson for QuickInputButtons with to_json(_self) {
  Json::null()
}

///|
pub impl Show for TabInputTerminal with output(_self, _logger) {

}

///|
pub impl Eq for TabInputTerminal with equal(lhs, rhs) {
  physical_equal(lhs, rhs)
}

///|
pub impl ToJson for TabInputTerminal with to_json(_self) {
  Json::null()
}

///|
pub impl Show for Memento with output(_self, _logger) {

}

///|
pub impl Eq for Memento with equal(lhs, rhs) {
  physical_equal(lhs, rhs)
}

///|
pub impl ToJson for Memento with to_json(_self) {
  Json::null()
}

///|
pub impl Show for CustomExecution with output(_self, _logger) {

}

///|
pub impl Eq for CustomExecution with equal(lhs, rhs) {
  physical_equal(lhs, rhs)
}

///|
pub impl ToJson for CustomExecution with to_json(_self) {
  Json::null()
}

///|
pub impl Show for ConfigurationChangeEvent with output(_self, _logger) {

}

///|
pub impl Eq for ConfigurationChangeEvent with equal(lhs, rhs) {
  physical_equal(lhs, rhs)
}

///|
pub impl ToJson for ConfigurationChangeEvent with to_json(_self) {
  Json::null()
}

///|
pub impl Show for ChatResponseStream with output(_self, _logger) {

}

///|
pub impl Eq for ChatResponseStream with equal(lhs, rhs) {
  physical_equal(lhs, rhs)
}

///|
pub impl ToJson for ChatResponseStream with to_json(_self) {
  Json::null()
}

///|
pub impl Show for WebviewPanelSerializer with output(_self, _logger) {

}

///|
pub impl Eq for WebviewPanelSerializer with equal(lhs, rhs) {
  physical_equal(lhs, rhs)
}

///|
pub impl ToJson for WebviewPanelSerializer with to_json(_self) {
  Json::null()
}

///|
pub impl Show for SemanticTokensBuilder with output(_self, _logger) {

}

///|
pub impl Eq for SemanticTokensBuilder with equal(lhs, rhs) {
  physical_equal(lhs, rhs)
}

///|
pub impl ToJson for SemanticTokensBuilder with to_json(_self) {
  Json::null()
}
