///|
#external
pub(all) type Disposable

///|
// TextEditorEdit interface with editing methods
#external
pub(all) type TextEditorEdit

///|
// Generic Any type placeholder

///|
// JavaScript RegExp object
#external
pub(all) type RegExp

///|
// Thenable represents a Promise-like object
#external
pub(all) type Thenable[T]

///|
// Event is a function interface for event listeners
#external
pub(all) type Event[T]

///|
#external
pub(all) type FileSystem

///|
#external
pub(all) type WorkspaceConfiguration

///|
#external
pub(all) type Progress[T]

///|
#external
pub(all) type QuickInputButtons

///|
#external
pub(all) type TabInputTerminal

///|
#external
pub(all) type Memento

///|
#external
pub(all) type CustomExecution

///|
#external
pub(all) type ConfigurationChangeEvent

///|
#external
pub(all) type ChatResponseStream

///|
#external
pub(all) type WebviewPanelSerializer

///|
#external
pub(all) type SemanticTokensBuilder
