///|
pub impl Show for Disposable with fn output(_self, _logger) {

}

///|
pub impl Eq for Disposable with fn equal(lhs, rhs) {
  physical_equal(lhs, rhs)
}

///|
pub impl ToJson for Disposable with fn to_json(_self) {
  Json::null()
}

///|
pub impl Show for TextEditorEdit with fn output(_self, _logger) {

}

///|
pub impl Eq for TextEditorEdit with fn equal(lhs, rhs) {
  physical_equal(lhs, rhs)
}

///|
pub impl ToJson for TextEditorEdit with fn to_json(_self) {
  Json::null()
}

///|
pub impl Show for RegExp with fn output(_self, _logger) {

}

///|
pub impl Eq for RegExp with fn equal(lhs, rhs) {
  physical_equal(lhs, rhs)
}

///|
pub impl ToJson for RegExp with fn to_json(_self) {
  Json::null()
}

///|
pub impl[T] Show for Thenable[T] with fn output(_self, _logger) {

}

///|
pub impl[T] Eq for Thenable[T] with fn equal(lhs, rhs) {
  physical_equal(lhs, rhs)
}

///|
pub impl[T] ToJson for Thenable[T] with fn to_json(_self) {
  Json::null()
}

///|
pub impl[T] Show for Event[T] with fn output(_self, _logger) {

}

///|
pub impl[T] Eq for Event[T] with fn equal(lhs, rhs) {
  physical_equal(lhs, rhs)
}

///|
pub impl[T] ToJson for Event[T] with fn to_json(_self) {
  Json::null()
}

///|
pub impl Show for FileSystem with fn output(_self, _logger) {

}

///|
pub impl Eq for FileSystem with fn equal(lhs, rhs) {
  physical_equal(lhs, rhs)
}

///|
pub impl ToJson for FileSystem with fn to_json(_self) {
  Json::null()
}

///|
pub impl Show for WorkspaceConfiguration with fn output(_self, _logger) {

}

///|
pub impl Eq for WorkspaceConfiguration with fn equal(lhs, rhs) {
  physical_equal(lhs, rhs)
}

///|
pub impl ToJson for WorkspaceConfiguration with fn to_json(_self) {
  Json::null()
}

///|
pub impl[T] Show for Progress[T] with fn output(_self, _logger) {

}

///|
pub impl[T] Eq for Progress[T] with fn equal(lhs, rhs) {
  physical_equal(lhs, rhs)
}

///|
pub impl[T] ToJson for Progress[T] with fn to_json(_self) {
  Json::null()
}

///|
pub impl Show for QuickInputButtons with fn output(_self, _logger) {

}

///|
pub impl Eq for QuickInputButtons with fn equal(lhs, rhs) {
  physical_equal(lhs, rhs)
}

///|
pub impl ToJson for QuickInputButtons with fn to_json(_self) {
  Json::null()
}

///|
pub impl Show for TabInputTerminal with fn output(_self, _logger) {

}

///|
pub impl Eq for TabInputTerminal with fn equal(lhs, rhs) {
  physical_equal(lhs, rhs)
}

///|
pub impl ToJson for TabInputTerminal with fn to_json(_self) {
  Json::null()
}

///|
pub impl Show for Memento with fn output(_self, _logger) {

}

///|
pub impl Eq for Memento with fn equal(lhs, rhs) {
  physical_equal(lhs, rhs)
}

///|
pub impl ToJson for Memento with fn to_json(_self) {
  Json::null()
}

///|
pub impl Show for CustomExecution with fn output(_self, _logger) {

}

///|
pub impl Eq for CustomExecution with fn equal(lhs, rhs) {
  physical_equal(lhs, rhs)
}

///|
pub impl ToJson for CustomExecution with fn to_json(_self) {
  Json::null()
}

///|
pub impl Show for ConfigurationChangeEvent with fn output(_self, _logger) {

}

///|
pub impl Eq for ConfigurationChangeEvent with fn equal(lhs, rhs) {
  physical_equal(lhs, rhs)
}

///|
pub impl ToJson for ConfigurationChangeEvent with fn to_json(_self) {
  Json::null()
}

///|
pub impl Show for ChatResponseStream with fn output(_self, _logger) {

}

///|
pub impl Eq for ChatResponseStream with fn equal(lhs, rhs) {
  physical_equal(lhs, rhs)
}

///|
pub impl ToJson for ChatResponseStream with fn to_json(_self) {
  Json::null()
}

///|
pub impl Show for WebviewPanelSerializer with fn output(_self, _logger) {

}

///|
pub impl Eq for WebviewPanelSerializer with fn equal(lhs, rhs) {
  physical_equal(lhs, rhs)
}

///|
pub impl ToJson for WebviewPanelSerializer with fn to_json(_self) {
  Json::null()
}

///|
pub impl Show for SemanticTokensBuilder with fn output(_self, _logger) {

}

///|
pub impl Eq for SemanticTokensBuilder with fn equal(lhs, rhs) {
  physical_equal(lhs, rhs)
}

///|
pub impl ToJson for SemanticTokensBuilder with fn to_json(_self) {
  Json::null()
}
