///|
/// R is result type 
/// E is element type of rest parameters
/// AN is argument types before rest parameters, e.g. A1, A2, ...
///

///|
#external
pub(all) type Func0Rest[R, E]

///|
#external
pub(all) type Func1Rest[R, E, A1]

///|
#external
pub(all) type Func2Rest[R, E, A1, A2]

///|
#external
pub(all) type Func3Rest[R, E, A1, A2, A3]

///|
#external
pub(all) type Func4Rest[R, E, A1, A2, A3, A4]

///|
#external
pub(all) type Func5Rest[R, E, A1, A2, A3, A4, A5]

///|
#external
pub(all) type Func6Rest[R, E, A1, A2, A3, A4, A5, A6]

///|
#external
pub(all) type Func7Rest[R, E, A1, A2, A3, A4, A5, A6, A7]

///|
#external
pub(all) type Func8Rest[R, E, A1, A2, A3, A4, A5, A6, A7, A8]

///|
#external
pub(all) type Func9Rest[R, E, A1, A2, A3, A4, A5, A6, A7, A8, A9]

///|
#external
pub(all) type Func10Rest[R, E, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10]

///|
#external
pub(all) type Func11Rest[R, E, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11]

///|
#external
pub(all) type Func12Rest[R, E, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12]

///|
#external
pub(all) type Func13Rest[R, E, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13]

///|
#external
pub(all) type Func14Rest[R, E, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14]

///|
#external
pub(all) type Func15Rest[R, E, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15]

///|
#external
pub(all) type Func16Rest[R, E, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16]
