///|
pub fn[R, E] Func0Rest::into(self : Func0Rest[R, E]) -> (Array[E]) -> R {
  coerce(func0rest_into)(self)
}

///|
pub fn[R, E, A1] Func1Rest::into(
  self : Func1Rest[R, E, A1],
) -> (A1, Array[E]) -> R {
  coerce(func1rest_into)(self)
}

///|
pub fn[R, E, A1, A2] Func2Rest::into(
  self : Func2Rest[R, E, A1, A2],
) -> (A1, A2, Array[E]) -> R {
  coerce(func2rest_into)(self)
}

///|
pub fn[R, E, A1, A2, A3] Func3Rest::into(
  self : Func3Rest[R, E, A1, A2, A3],
) -> (A1, A2, A3, Array[E]) -> R {
  coerce(func3rest_into)(self)
}

///|
pub fn[R, E, A1, A2, A3, A4] Func4Rest::into(
  self : Func4Rest[R, E, A1, A2, A3, A4],
) -> (A1, A2, A3, A4, Array[E]) -> R {
  coerce(func4rest_into)(self)
}

///|
pub fn[R, E, A1, A2, A3, A4, A5] Func5Rest::into(
  self : Func5Rest[R, E, A1, A2, A3, A4, A5],
) -> (A1, A2, A3, A4, A5, Array[E]) -> R {
  coerce(func5rest_into)(self)
}

///|
pub fn[R, E, A1, A2, A3, A4, A5, A6] Func6Rest::into(
  self : Func6Rest[R, E, A1, A2, A3, A4, A5, A6],
) -> (A1, A2, A3, A4, A5, A6, Array[E]) -> R {
  coerce(func6rest_into)(self)
}

///|
pub fn[R, E, A1, A2, A3, A4, A5, A6, A7] Func7Rest::into(
  self : Func7Rest[R, E, A1, A2, A3, A4, A5, A6, A7],
) -> (A1, A2, A3, A4, A5, A6, A7, Array[E]) -> R {
  coerce(func7rest_into)(self)
}

///|
pub fn[R, E, A1, A2, A3, A4, A5, A6, A7, A8] Func8Rest::into(
  self : Func8Rest[R, E, A1, A2, A3, A4, A5, A6, A7, A8],
) -> (A1, A2, A3, A4, A5, A6, A7, A8, Array[E]) -> R {
  coerce(func8rest_into)(self)
}

///|
pub fn[R, E, A1, A2, A3, A4, A5, A6, A7, A8, A9] Func9Rest::into(
  self : Func9Rest[R, E, A1, A2, A3, A4, A5, A6, A7, A8, A9],
) -> (A1, A2, A3, A4, A5, A6, A7, A8, A9, Array[E]) -> R {
  coerce(func9rest_into)(self)
}

///|
pub fn[R, E, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10] Func10Rest::into(
  self : Func10Rest[R, E, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10],
) -> (A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, Array[E]) -> R {
  coerce(func10rest_into)(self)
}

///|
pub fn[R, E, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11] Func11Rest::into(
  self : Func11Rest[R, E, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11],
) -> (A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, Array[E]) -> R {
  coerce(func11rest_into)(self)
}

///|
pub fn[R, E, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12] Func12Rest::into(
  self : Func12Rest[R, E, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12],
) -> (A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, Array[E]) -> R {
  coerce(func12rest_into)(self)
}

///|
pub fn[R, E, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13] Func13Rest::into(
  self : Func13Rest[
    R,
    E,
    A1,
    A2,
    A3,
    A4,
    A5,
    A6,
    A7,
    A8,
    A9,
    A10,
    A11,
    A12,
    A13,
  ],
) -> (A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, Array[E]) -> R {
  coerce(func13rest_into)(self)
}

///|
pub fn[R, E, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14] Func14Rest::into(
  self : Func14Rest[
    R,
    E,
    A1,
    A2,
    A3,
    A4,
    A5,
    A6,
    A7,
    A8,
    A9,
    A10,
    A11,
    A12,
    A13,
    A14,
  ],
) -> (A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, Array[E]) -> R {
  coerce(func14rest_into)(self)
}

///|
pub fn[R, E, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15] Func15Rest::into(
  self : Func15Rest[
    R,
    E,
    A1,
    A2,
    A3,
    A4,
    A5,
    A6,
    A7,
    A8,
    A9,
    A10,
    A11,
    A12,
    A13,
    A14,
    A15,
  ],
) -> (
  A1,
  A2,
  A3,
  A4,
  A5,
  A6,
  A7,
  A8,
  A9,
  A10,
  A11,
  A12,
  A13,
  A14,
  A15,
  Array[E],
) -> R {
  coerce(func15rest_into)(self)
}

///|
pub fn[
  R,
  E,
  A1,
  A2,
  A3,
  A4,
  A5,
  A6,
  A7,
  A8,
  A9,
  A10,
  A11,
  A12,
  A13,
  A14,
  A15,
  A16,
] Func16Rest::into(
  self : Func16Rest[
    R,
    E,
    A1,
    A2,
    A3,
    A4,
    A5,
    A6,
    A7,
    A8,
    A9,
    A10,
    A11,
    A12,
    A13,
    A14,
    A15,
    A16,
  ],
) -> (
  A1,
  A2,
  A3,
  A4,
  A5,
  A6,
  A7,
  A8,
  A9,
  A10,
  A11,
  A12,
  A13,
  A14,
  A15,
  A16,
  Array[E],
) -> R {
  coerce(func16rest_into)(self)
}
