///|
pub impl[R, E] Show for Func0Rest[R, E] with output(_self, _logger) {

}

///|
pub impl[R, E] Eq for Func0Rest[R, E] with equal(lhs, rhs) {
  physical_equal(lhs, rhs)
}

///|
pub impl[R, E] ToJson for Func0Rest[R, E] with to_json(_self) {
  Json::null()
}

///|
pub impl[R, E, A1] Show for Func1Rest[R, E, A1] with output(_self, _logger) {

}

///|
pub impl[R, E, A1] Eq for Func1Rest[R, E, A1] with equal(lhs, rhs) {
  physical_equal(lhs, rhs)
}

///|
pub impl[R, E, A1] ToJson for Func1Rest[R, E, A1] with to_json(_self) {
  Json::null()
}

///|
pub impl[R, E, A1, A2] Show for Func2Rest[R, E, A1, A2] with output(
  _self,
  _logger,
) {

}

///|
pub impl[R, E, A1, A2] Eq for Func2Rest[R, E, A1, A2] with equal(lhs, rhs) {
  physical_equal(lhs, rhs)
}

///|
pub impl[R, E, A1, A2] ToJson for Func2Rest[R, E, A1, A2] with to_json(_self) {
  Json::null()
}

///|
pub impl[R, E, A1, A2, A3] Show for Func3Rest[R, E, A1, A2, A3] with output(
  _self,
  _logger,
) {

}

///|
pub impl[R, E, A1, A2, A3] Eq for Func3Rest[R, E, A1, A2, A3] with equal(
  lhs,
  rhs,
) {
  physical_equal(lhs, rhs)
}

///|
pub impl[R, E, A1, A2, A3] ToJson for Func3Rest[R, E, A1, A2, A3] with to_json(
  _self,
) {
  Json::null()
}

///|
pub impl[R, E, A1, A2, A3, A4] Show for Func4Rest[R, E, A1, A2, A3, A4] with output(
  _self,
  _logger,
) {

}

///|
pub impl[R, E, A1, A2, A3, A4] Eq for Func4Rest[R, E, A1, A2, A3, A4] with equal(
  lhs,
  rhs,
) {
  physical_equal(lhs, rhs)
}

///|
pub impl[R, E, A1, A2, A3, A4] ToJson for Func4Rest[R, E, A1, A2, A3, A4] with to_json(
  _self,
) {
  Json::null()
}

///|
pub impl[R, E, A1, A2, A3, A4, A5] Show for Func5Rest[R, E, A1, A2, A3, A4, A5] with output(
  _self,
  _logger,
) {

}

///|
pub impl[R, E, A1, A2, A3, A4, A5] Eq for Func5Rest[R, E, A1, A2, A3, A4, A5] with equal(
  lhs,
  rhs,
) {
  physical_equal(lhs, rhs)
}

///|
pub impl[R, E, A1, A2, A3, A4, A5] ToJson for Func5Rest[
  R,
  E,
  A1,
  A2,
  A3,
  A4,
  A5,
] with to_json(_self) {
  Json::null()
}

///|
pub impl[R, E, A1, A2, A3, A4, A5, A6] Show for Func6Rest[
  R,
  E,
  A1,
  A2,
  A3,
  A4,
  A5,
  A6,
] with output(_self, _logger) {

}

///|
pub impl[R, E, A1, A2, A3, A4, A5, A6] Eq for Func6Rest[
  R,
  E,
  A1,
  A2,
  A3,
  A4,
  A5,
  A6,
] with equal(lhs, rhs) {
  physical_equal(lhs, rhs)
}

///|
pub impl[R, E, A1, A2, A3, A4, A5, A6] ToJson for Func6Rest[
  R,
  E,
  A1,
  A2,
  A3,
  A4,
  A5,
  A6,
] with to_json(_self) {
  Json::null()
}

///|
pub impl[R, E, A1, A2, A3, A4, A5, A6, A7] Show for Func7Rest[
  R,
  E,
  A1,
  A2,
  A3,
  A4,
  A5,
  A6,
  A7,
] with output(_self, _logger) {

}

///|
pub impl[R, E, A1, A2, A3, A4, A5, A6, A7] Eq for Func7Rest[
  R,
  E,
  A1,
  A2,
  A3,
  A4,
  A5,
  A6,
  A7,
] with equal(lhs, rhs) {
  physical_equal(lhs, rhs)
}

///|
pub impl[R, E, A1, A2, A3, A4, A5, A6, A7] ToJson for Func7Rest[
  R,
  E,
  A1,
  A2,
  A3,
  A4,
  A5,
  A6,
  A7,
] with to_json(_self) {
  Json::null()
}

///|
pub impl[R, E, A1, A2, A3, A4, A5, A6, A7, A8] Show for Func8Rest[
  R,
  E,
  A1,
  A2,
  A3,
  A4,
  A5,
  A6,
  A7,
  A8,
] with output(_self, _logger) {

}

///|
pub impl[R, E, A1, A2, A3, A4, A5, A6, A7, A8] Eq for Func8Rest[
  R,
  E,
  A1,
  A2,
  A3,
  A4,
  A5,
  A6,
  A7,
  A8,
] with equal(lhs, rhs) {
  physical_equal(lhs, rhs)
}

///|
pub impl[R, E, A1, A2, A3, A4, A5, A6, A7, A8] ToJson for Func8Rest[
  R,
  E,
  A1,
  A2,
  A3,
  A4,
  A5,
  A6,
  A7,
  A8,
] with to_json(_self) {
  Json::null()
}

///|
pub impl[R, E, A1, A2, A3, A4, A5, A6, A7, A8, A9] Show for Func9Rest[
  R,
  E,
  A1,
  A2,
  A3,
  A4,
  A5,
  A6,
  A7,
  A8,
  A9,
] with output(_self, _logger) {

}

///|
pub impl[R, E, A1, A2, A3, A4, A5, A6, A7, A8, A9] Eq for Func9Rest[
  R,
  E,
  A1,
  A2,
  A3,
  A4,
  A5,
  A6,
  A7,
  A8,
  A9,
] with equal(lhs, rhs) {
  physical_equal(lhs, rhs)
}

///|
pub impl[R, E, A1, A2, A3, A4, A5, A6, A7, A8, A9] ToJson for Func9Rest[
  R,
  E,
  A1,
  A2,
  A3,
  A4,
  A5,
  A6,
  A7,
  A8,
  A9,
] with to_json(_self) {
  Json::null()
}

///|
pub impl[R, E, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10] Show for Func10Rest[
  R,
  E,
  A1,
  A2,
  A3,
  A4,
  A5,
  A6,
  A7,
  A8,
  A9,
  A10,
] with output(_self, _logger) {

}

///|
pub impl[R, E, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10] Eq for Func10Rest[
  R,
  E,
  A1,
  A2,
  A3,
  A4,
  A5,
  A6,
  A7,
  A8,
  A9,
  A10,
] with equal(lhs, rhs) {
  physical_equal(lhs, rhs)
}

///|
pub impl[R, E, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10] ToJson for Func10Rest[
  R,
  E,
  A1,
  A2,
  A3,
  A4,
  A5,
  A6,
  A7,
  A8,
  A9,
  A10,
] with to_json(_self) {
  Json::null()
}

///|
pub impl[R, E, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11] Show for Func11Rest[
  R,
  E,
  A1,
  A2,
  A3,
  A4,
  A5,
  A6,
  A7,
  A8,
  A9,
  A10,
  A11,
] with output(_self, _logger) {

}

///|
pub impl[R, E, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11] Eq for Func11Rest[
  R,
  E,
  A1,
  A2,
  A3,
  A4,
  A5,
  A6,
  A7,
  A8,
  A9,
  A10,
  A11,
] with equal(lhs, rhs) {
  physical_equal(lhs, rhs)
}

///|
pub impl[R, E, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11] ToJson for Func11Rest[
  R,
  E,
  A1,
  A2,
  A3,
  A4,
  A5,
  A6,
  A7,
  A8,
  A9,
  A10,
  A11,
] with to_json(_self) {
  Json::null()
}

///|
pub impl[R, E, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12] Show for Func12Rest[
  R,
  E,
  A1,
  A2,
  A3,
  A4,
  A5,
  A6,
  A7,
  A8,
  A9,
  A10,
  A11,
  A12,
] with output(_self, _logger) {

}

///|
pub impl[R, E, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12] Eq for Func12Rest[
  R,
  E,
  A1,
  A2,
  A3,
  A4,
  A5,
  A6,
  A7,
  A8,
  A9,
  A10,
  A11,
  A12,
] with equal(lhs, rhs) {
  physical_equal(lhs, rhs)
}

///|
pub impl[R, E, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12] ToJson for Func12Rest[
  R,
  E,
  A1,
  A2,
  A3,
  A4,
  A5,
  A6,
  A7,
  A8,
  A9,
  A10,
  A11,
  A12,
] with to_json(_self) {
  Json::null()
}

///|
pub impl[R, E, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13] Show for Func13Rest[
  R,
  E,
  A1,
  A2,
  A3,
  A4,
  A5,
  A6,
  A7,
  A8,
  A9,
  A10,
  A11,
  A12,
  A13,
] with output(_self, _logger) {

}

///|
pub impl[R, E, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13] Eq for Func13Rest[
  R,
  E,
  A1,
  A2,
  A3,
  A4,
  A5,
  A6,
  A7,
  A8,
  A9,
  A10,
  A11,
  A12,
  A13,
] with equal(lhs, rhs) {
  physical_equal(lhs, rhs)
}

///|
pub impl[R, E, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13] ToJson for Func13Rest[
  R,
  E,
  A1,
  A2,
  A3,
  A4,
  A5,
  A6,
  A7,
  A8,
  A9,
  A10,
  A11,
  A12,
  A13,
] with to_json(_self) {
  Json::null()
}

///|
pub impl[R, E, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14] Show for Func14Rest[
  R,
  E,
  A1,
  A2,
  A3,
  A4,
  A5,
  A6,
  A7,
  A8,
  A9,
  A10,
  A11,
  A12,
  A13,
  A14,
] with output(_self, _logger) {

}

///|
pub impl[R, E, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14] Eq for Func14Rest[
  R,
  E,
  A1,
  A2,
  A3,
  A4,
  A5,
  A6,
  A7,
  A8,
  A9,
  A10,
  A11,
  A12,
  A13,
  A14,
] with equal(lhs, rhs) {
  physical_equal(lhs, rhs)
}

///|
pub impl[R, E, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14] ToJson for Func14Rest[
  R,
  E,
  A1,
  A2,
  A3,
  A4,
  A5,
  A6,
  A7,
  A8,
  A9,
  A10,
  A11,
  A12,
  A13,
  A14,
] with to_json(_self) {
  Json::null()
}

///|
pub impl[R, E, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15] Show for Func15Rest[
  R,
  E,
  A1,
  A2,
  A3,
  A4,
  A5,
  A6,
  A7,
  A8,
  A9,
  A10,
  A11,
  A12,
  A13,
  A14,
  A15,
] with output(_self, _logger) {

}

///|
pub impl[R, E, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15] Eq for Func15Rest[
  R,
  E,
  A1,
  A2,
  A3,
  A4,
  A5,
  A6,
  A7,
  A8,
  A9,
  A10,
  A11,
  A12,
  A13,
  A14,
  A15,
] with equal(lhs, rhs) {
  physical_equal(lhs, rhs)
}

///|
pub impl[R, E, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15] ToJson for Func15Rest[
  R,
  E,
  A1,
  A2,
  A3,
  A4,
  A5,
  A6,
  A7,
  A8,
  A9,
  A10,
  A11,
  A12,
  A13,
  A14,
  A15,
] with to_json(_self) {
  Json::null()
}

///|
pub impl[
  R,
  E,
  A1,
  A2,
  A3,
  A4,
  A5,
  A6,
  A7,
  A8,
  A9,
  A10,
  A11,
  A12,
  A13,
  A14,
  A15,
  A16,
] Show for Func16Rest[
  R,
  E,
  A1,
  A2,
  A3,
  A4,
  A5,
  A6,
  A7,
  A8,
  A9,
  A10,
  A11,
  A12,
  A13,
  A14,
  A15,
  A16,
] with output(_self, _logger) {

}

///|
pub impl[
  R,
  E,
  A1,
  A2,
  A3,
  A4,
  A5,
  A6,
  A7,
  A8,
  A9,
  A10,
  A11,
  A12,
  A13,
  A14,
  A15,
  A16,
] Eq for Func16Rest[
  R,
  E,
  A1,
  A2,
  A3,
  A4,
  A5,
  A6,
  A7,
  A8,
  A9,
  A10,
  A11,
  A12,
  A13,
  A14,
  A15,
  A16,
] with equal(lhs, rhs) {
  physical_equal(lhs, rhs)
}

///|
pub impl[
  R,
  E,
  A1,
  A2,
  A3,
  A4,
  A5,
  A6,
  A7,
  A8,
  A9,
  A10,
  A11,
  A12,
  A13,
  A14,
  A15,
  A16,
] ToJson for Func16Rest[
  R,
  E,
  A1,
  A2,
  A3,
  A4,
  A5,
  A6,
  A7,
  A8,
  A9,
  A10,
  A11,
  A12,
  A13,
  A14,
  A15,
  A16,
] with to_json(_self) {
  Json::null()
}
