///|
/// Keeps trait methods available through dot syntax.
pub extend Func0Rest with Show::{to_string, output}

///|
pub extend Func0Rest with Eq::{not_equal, equal}

///|
pub extend Func0Rest with ToJson::{to_json}

///|
pub extend Func1Rest with Show::{to_string, output}

///|
pub extend Func1Rest with Eq::{not_equal, equal}

///|
pub extend Func1Rest with ToJson::{to_json}

///|
pub extend Func2Rest with Show::{to_string, output}

///|
pub extend Func2Rest with Eq::{not_equal, equal}

///|
pub extend Func2Rest with ToJson::{to_json}

///|
pub extend Func3Rest with Show::{to_string, output}

///|
pub extend Func3Rest with Eq::{not_equal, equal}

///|
pub extend Func3Rest with ToJson::{to_json}

///|
pub extend Func4Rest with Show::{to_string, output}

///|
pub extend Func4Rest with Eq::{not_equal, equal}

///|
pub extend Func4Rest with ToJson::{to_json}

///|
pub extend Func5Rest with Show::{to_string, output}

///|
pub extend Func5Rest with Eq::{not_equal, equal}

///|
pub extend Func5Rest with ToJson::{to_json}

///|
pub extend Func6Rest with Show::{to_string, output}

///|
pub extend Func6Rest with Eq::{not_equal, equal}

///|
pub extend Func6Rest with ToJson::{to_json}

///|
pub extend Func7Rest with Show::{to_string, output}

///|
pub extend Func7Rest with Eq::{not_equal, equal}

///|
pub extend Func7Rest with ToJson::{to_json}

///|
pub extend Func8Rest with Show::{to_string, output}

///|
pub extend Func8Rest with Eq::{not_equal, equal}

///|
pub extend Func8Rest with ToJson::{to_json}

///|
pub extend Func9Rest with Show::{to_string, output}

///|
pub extend Func9Rest with Eq::{not_equal, equal}

///|
pub extend Func9Rest with ToJson::{to_json}

///|
pub extend Func10Rest with Show::{to_string, output}

///|
pub extend Func10Rest with Eq::{not_equal, equal}

///|
pub extend Func10Rest with ToJson::{to_json}

///|
pub extend Func11Rest with Show::{to_string, output}

///|
pub extend Func11Rest with Eq::{not_equal, equal}

///|
pub extend Func11Rest with ToJson::{to_json}

///|
pub extend Func12Rest with Show::{to_string, output}

///|
pub extend Func12Rest with Eq::{not_equal, equal}

///|
pub extend Func12Rest with ToJson::{to_json}

///|
pub extend Func13Rest with Show::{to_string, output}

///|
pub extend Func13Rest with Eq::{not_equal, equal}

///|
pub extend Func13Rest with ToJson::{to_json}

///|
pub extend Func14Rest with Show::{to_string, output}

///|
pub extend Func14Rest with Eq::{not_equal, equal}

///|
pub extend Func14Rest with ToJson::{to_json}

///|
pub extend Func15Rest with Show::{to_string, output}

///|
pub extend Func15Rest with Eq::{not_equal, equal}

///|
pub extend Func15Rest with ToJson::{to_json}

///|
pub extend Func16Rest with Show::{to_string, output}

///|
pub extend Func16Rest with Eq::{not_equal, equal}

///|
pub extend Func16Rest with ToJson::{to_json}

///|
pub extend Any with Show::{to_string, output}

///|
pub extend Any with Eq::{not_equal, equal}

///|
pub extend Any with ToJson::{to_json}

///|
pub extend Union2 with Show::{to_string, output}

///|
pub extend Union2 with Eq::{not_equal, equal}

///|
pub extend Union2 with ToJson::{to_json}

///|
pub extend Union3 with Show::{to_string, output}

///|
pub extend Union3 with Eq::{not_equal, equal}

///|
pub extend Union3 with ToJson::{to_json}

///|
pub extend Union4 with Show::{to_string, output}

///|
pub extend Union4 with Eq::{not_equal, equal}

///|
pub extend Union4 with ToJson::{to_json}

///|
pub extend Union5 with Show::{to_string, output}

///|
pub extend Union5 with Eq::{not_equal, equal}

///|
pub extend Union5 with ToJson::{to_json}

///|
pub extend Union6 with Show::{to_string, output}

///|
pub extend Union6 with Eq::{not_equal, equal}

///|
pub extend Union6 with ToJson::{to_json}

///|
pub extend Union7 with Show::{to_string, output}

///|
pub extend Union7 with Eq::{not_equal, equal}

///|
pub extend Union7 with ToJson::{to_json}

///|
pub extend Union8 with Show::{to_string, output}

///|
pub extend Union8 with Eq::{not_equal, equal}

///|
pub extend Union8 with ToJson::{to_json}

///|
pub extend Union9 with Show::{to_string, output}

///|
pub extend Union9 with Eq::{not_equal, equal}

///|
pub extend Union9 with ToJson::{to_json}

///|
pub extend Union10 with Show::{to_string, output}

///|
pub extend Union10 with Eq::{not_equal, equal}

///|
pub extend Union10 with ToJson::{to_json}

///|
pub extend Union11 with Show::{to_string, output}

///|
pub extend Union11 with Eq::{not_equal, equal}

///|
pub extend Union11 with ToJson::{to_json}

///|
pub extend Union12 with Show::{to_string, output}

///|
pub extend Union12 with Eq::{not_equal, equal}

///|
pub extend Union12 with ToJson::{to_json}

///|
pub extend Union13 with Show::{to_string, output}

///|
pub extend Union13 with Eq::{not_equal, equal}

///|
pub extend Union13 with ToJson::{to_json}

///|
pub extend Union14 with Show::{to_string, output}

///|
pub extend Union14 with Eq::{not_equal, equal}

///|
pub extend Union14 with ToJson::{to_json}

///|
pub extend Union15 with Show::{to_string, output}

///|
pub extend Union15 with Eq::{not_equal, equal}

///|
pub extend Union15 with ToJson::{to_json}

///|
pub extend Union16 with Show::{to_string, output}

///|
pub extend Union16 with Eq::{not_equal, equal}

///|
pub extend Union16 with ToJson::{to_json}
