///|
#external
pub(all) type Any

///|
#external
pub(all) type Union2[_, _]

///|
#external
pub(all) type Union3[_, _, _]

///|
#external
pub(all) type Union4[_, _, _, _]

///|
#external
pub(all) type Union5[_, _, _, _, _]

///|
#external
pub(all) type Union6[_, _, _, _, _, _]

///|
#external
pub(all) type Union7[_, _, _, _, _, _, _]

///|
#external
pub(all) type Union8[_, _, _, _, _, _, _, _]

///|
#external
pub(all) type Union9[_, _, _, _, _, _, _, _, _]

///|
#external
pub(all) type Union10[_, _, _, _, _, _, _, _, _, _]

///|
#external
pub(all) type Union11[_, _, _, _, _, _, _, _, _, _, _]

///|
#external
pub(all) type Union12[_, _, _, _, _, _, _, _, _, _, _, _]

///|
#external
pub(all) type Union13[_, _, _, _, _, _, _, _, _, _, _, _, _]

///|
#external
pub(all) type Union14[_, _, _, _, _, _, _, _, _, _, _, _, _, _]

///|
#external
pub(all) type Union15[_, _, _, _, _, _, _, _, _, _, _, _, _, _, _]

///|
#external
pub(all) type Union16[_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _]
